source "https://rubygems.org"

# Specify your Ruby dependencies here:
gem "rails", "~> 7.1.0"
gem "puma", ">= 5.0"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use Redis adapter to run Action Cable in production
gem "redis", ">= 4.0.1"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# GraphQL
gem "graphql", "~> 2.0"
gem "graphql-batch"
gem "globalid"
gem "nokogiri"
gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ]
  gem "database_cleaner-active_record"
  gem "factory_bot_rails"
  gem "faker"
  gem "rspec-rails"
  gem "webmock"
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  gem "rubocop", require: false
  gem "rubocop-factory_bot", require: false
  gem "rubocop-graphql", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end
